# Continuous Integration (CI) pipeline that orchestrates the training, evaluation, and registration of the AviationMLOps model.

resources:
  containers:
  - container: mlops
    image: mcr.microsoft.com/mlops/python:latest

pr: none
trigger: none

variables:
- group: devopsforai-aml-vg

pool:
  vmImage: ubuntu-latest

jobs:
- job: "Model_Deploy_Pipeline"
  displayName: "Model Deploy Pipeline"
  container: mlops
  timeoutInMinutes: 0
  steps:
  - template: ./templates/deploy.yml